### ISSUE TITLE
What environment variables are available?

### ISSUE THREAD

**Issue by johnennewdeeson** [pantheon-systems/quicksilver-examples#105]
Are any environment variables available to our scripts? Specifically I would like to know which environment the script is being run on (dev, test, live, or which multidev).  

This might be the uri for the environment, e.g. test-mysite.pantheonsite.io

**Comment by greg-1-anderson** [comment]
Install the debug example and run it; it will display all of the available environment variables.

Here's some really old output; current might be slightly different.
```
---------- ENVIRONMNET ------------
DB_HOST=...
DB_NAME=pantheon
DB_PORT=10022
PANTHEON_ENVIRONMENT=dev
USER=...
PATH=...
PANTHEON_SITE=...
DOCROOT=/
PWD=...
DB_PASSWORD=...
DRUPAL_HASH_SALT=...
PANTHEON_SITE_NAME=...
SHLVL=1
FILEMOUNT=sites/default/files
HOME=...
DB_USER=pantheon
FRAMEWORK=drupal
PANTHEON_INFRASTRUCTURE_ENVIRONMENT=...
_=/bin/printenv
```
For speedy Quicksilver development, try the [Terminus Quicksilver Plugin](https://github.com/pantheon-systems/terminus-quicksilver-plugin)

**Comment by greg-1-anderson** [comment]
`PANTHEON_ENVIRONMENT` is what you are looking for, btw

**Comment by greg-1-anderson** [comment]
n.b. some of this information is also available in the Quicksilver payload:
```
========= START PAYLOAD ===========
Array
(
    [wf_type] => clear_cache
    [user_id] => ...
    [site_id] => ...
    [user_role] => super
    [trace_id] => ...
    [environment] => dev
    [wf_description] => Clear cache for "dev"
    [user_email] => ...
)
```

**Comment by johnennewdeeson** [comment]
Thanks for the speedy response! Just what I was after - I've suggested a change to the README to point others to this very useful debug script, I thought it should be highlighted from the first README for script developers.  https://github.com/pantheon-systems/quicksilver-examples/pull/106
