### ISSUE TITLE
Can sync_code detect a git tag creation?

### ISSUE THREAD

**Issue by gxof** [pantheon-systems/quicksilver-examples#119]
Hello;

I don't know if it is an issue and I am unsure of here being the right place to ask for help (or pantheon support?). 

Is there a way to hook, not on a git commit but on a git tag creation?

my workflow:

> 
> workflows:
>  sync_code:
>    after:
>        - type: webphp
>          description: Notification.
>          script: private/scripts/my_script.php

is working well when there is a commit. But nothing is happening for tag, sync_code does not seem to capture their creation.

Is there a way to do so? 

Gerald

**Comment by kyletaylored** [comment]
I don't believe this is possible today and is not on the roadmap.
