### ISSUE TITLE
undefined variable: deploy tag in new_relic_deploy.php script

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/quicksilver-examples#135]
Getting the following notice after deploying code changes to Test env.

`Undefined variable: deploy_tag in /srv/bindings/ed851365e8b24fbdb2c5e19bbe784cab/code/private/scripts/new_relic_deploy.php on line 51`

It seems to be working in Live.

Any thoughts?

**Comment by TimVu** [comment]
+1

Thanks for getting this issue posted!

**Comment by ataylorme** [comment]
Thanks for the report, this should be fixed with #115
