### ISSUE TITLE
diffy.website integration is unnecessarily tedious

### ISSUE THREAD

**Issue by miiimooo** [pantheon-systems/quicksilver-examples#174]
I've tested the diffy.website integration and though on paper it looks great in reality it's a big hassle and won't work as you would expect (https://github.com/pantheon-systems/quicksilver-examples/tree/main/diffy_visualregression)

A conceptual issue I found with it is that it should trigger after a deploy but also including a db clone. Otherwise the comparison doesn't make sense. `test` and `live` need to be copies of each other for this to be useful.

At the moment, the included example triggers on deploy.after - but this doesn't trigger when the deploy+database/file cloning is done. It triggers before that. This way deploys to test become a two step process: clone db and files, then deploy. It would be much more useful if this could be done just in one step and help to automate testing

**Comment by greg-1-anderson** [comment]
The purpose of the examples here are only to show how to integrate with different services; the diffy visual regression example is not intended to be a full vrt product.

See the Pantheon [Autopilot](https://pantheon.io/autopilot) product for a more packaged solution.
