### ISSUE TITLE
Example wanted: ping out to a visual diff service(s)

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/quicksilver-examples#21]
There are a few good ones out there:

http://backtrac.io/documentation/rest-api

https://eyes.applitools.com/app/tutorial.html

It'd be awesome to kick off a test automatically when there's a new deploy into the test environment!

**Comment by populist** [comment]
Here is a PR for integration with Backtrac.io: https://github.com/pantheon-systems/quicksilver-examples/pull/68

**Comment by populist** [comment]
And here is a PR for integration with Spotbot.qa: https://github.com/pantheon-systems/quicksilver-examples/pull/69
