### ISSUE TITLE
Documentation unclear on script placement

### ISSUE THREAD

**Issue by jordan8037310** [pantheon-systems/quicksilver-examples#24]
Hello,

I was trying to test out the provided slack notification quicksilver examples and was a bit confused as you speak about the repository and the private files repo at different locations.

Should I be storing the slack notification in:

{repo root}/private/scripts/slack_after_deploy.php?

Or do you mean for me to run the ftp command to deploy the php to the private files folder similar to the JSON with secret?

**Comment by bmackinney** [comment]
You're right. They belong in different locations. php in `~/code/private/<scripts>/`, and `secrets.json` in `~/files/private`. Can you link me to the line that was unclear?

**Comment by jordan8037310** [comment]
Here is the section:
--
Quicksilver scripts should be tracked in the private directory of your project repository, which is not accessible to the public Internet. Scripts there can only be executed by the Pantheon platform. We recommend setting up a dedicated directory (e.g. private/scripts or private/quicksilver) for tracking these files.
--
Also, it is unclear to me how the "private" repo is actually private. Do I need to commit a .htaccess that Denies All? Does the platform handle this?

**Comment by bmackinney** [comment]
That's right, the platform's nginx configuration handles this automatically. Inside of Drupal or WordPress, (`~/code/`), the `~/code/private/` and `~/files/private` directories are private by default.

**Comment by jordan8037310** [comment]
Hmmm interesting, even with the appropriate location I'm not getting anything. Where can I see logs for errors? e.g. workflow tasks executed?

I tried installing the workflow-cli but received some errors there which I just reported on that repo

**Comment by aaronbauman** [comment]
I'm experiencing the same symptoms.
I've copied everything directly from the debug setup.
`terminus workflows` shows that the workflows are executing
... but there's no output from debug.php

My directory structure is just as described:
```
code/
  pantheon.yml
  private/
    scripts/
      debug.php 
```

Other, possibly-related notes:
- I had to `git add -f` private directory
- when connected via SFTP, private directory did not appear until i attempted `mkdir`
- I have tried moving debug.php to `code/private/scripts/debug.php`, `private/scripts/debug.php`, and `code/quicksilver/debug.php` each time updating pantheon.yml accordingly and all to no avail.
- I have tried moving pantheon.yml up to the SFTP root, also to no avail

**Comment by greg-1-anderson** [comment]
`pantheon.yml` and `private` directories go at your repository root (`code`). Your steps above all look correct; did you put your site into `git` mode, commit your code and push up to Pantheon?  You might also want to try using [quicksilver-cli](https://github.com/pantheon-systems/quicksilver-cli), which drops everything in exactly where it belongs. Just run `cd /my/local/site/clone` and `quicksilver install debug`.

Try creating a brand-new site on Pantheon, and set it up with the debug script, and see if it works there. Sometimes, sites can get "wedged", and Quicksilver scripts stop running there. Converge does not always fix Quicksilver problems. This will be fixed in the future.

**Comment by aaronbauman** [comment]
I did try installing quicksilver-cli, and none of the symptoms were resolved.

This is a brand new site as of this morning, created via a drush archive import, but I will try with a new one from scratch.

Is there a resolution for "un-wedging" this site?
Some magic word for a support ticket?
Re-creating all my sites is not exactly a scalable solution.

**Comment by greg-1-anderson** [comment]
The resolution is that the Quicksilver setup all needs to be done in the "converge" process. This is still a work-in-progress.

I don't know if there is any problem with importing a site an Quicksilver (I presume you are importing a drops-based site), but please try with a test site created and installed on Pantheon, and see if that works.

**Comment by aaronbauman** [comment]
yeah, it works great on a clean install.

I think my problem was _not_ using a drops-based site.
I'll take a look at the delta between the clean install and my non-working install to see if what's missing in the drupal codebase.

Could it be simply a matter of enabling the drupal pantheon modules?

**Comment by greg-1-anderson** [comment]
drops-7 is based on Pressflow, and has other core modifications in addition to the pantheon modules. I'd recommend starting with a Pantheon-installed site, and then copy in your contrib modules from `sites/all`. Once you do this, it should be possible to import your database.

If your site is small, you might also try importing it from the Dashboard when you create a new site. The new-site import tool should fix up your core and turn it into a Pantheon-based site. This process does not work if your database is too large, though.

**Comment by aaronbauman** [comment]
Might be worth adding something like this to the README:

You will know your pantheon.yml file has been added correctly, and your quicksilver actions are registered if you get the following message on `git push`
```
remote: 
remote: PANTHEON NOTICE:
remote: 
remote: Changes to `pantheon.yml` detected.
remote: 
remote: Successfully applied `pantheon.yml` to the 'dev' environment.
remote: 
remote: 
```

**Comment by greg-1-anderson** [comment]
+1 on documentation suggestion.
