### ISSUE TITLE
Documentation for self-referential updates to scripts / pantheon.yml

### ISSUE THREAD

**Issue by jordan8037310** [pantheon-systems/quicksilver-examples#27]
While working on updating slack to use attachments, I saw behavior that is inconsistent with the following statement in the documentation:

"Likewise, if you are adding new operations or changing the script an operation will target, the deploy which contains those adjustments to pantheon.yml will not self-referentially exhibit the new behavior. Only subsequent deploys will be affected."

Just to clarify, updates made to the referenced scripts are executing for me on the first push, but the statement here refers to the registry of which scripts to run within pantheon.yml, and how they don't run self-referentially on the same commit, correct?

Or is it perhaps it's the fact that I've been working on a script that fires _after_ deploy?

**Comment by joshkoenig** [comment]
> Or is it perhaps it's the fact that I've been working on a script that fires after deploy?

If you make changes to a script, and you trigger that script _after_ deploy, then you can see your changes immediately.

However, if you add a new workflow or script, or change a script location, or you are deploying a `pantheon.yml` that ties a script to the `deploy` workfow into a new environment, you won't see any of that fire until the next workflow. 

Agreed this could be a little clearer. Thanks for all your suggestions, BTW!

**Comment by jordan8037310** [comment]
No problem, I'd suggest displaying this as a table.

When Updating
pantheon.yml - Updates will fire on the next sequential workflow, not post-deploy.
scripts - Updates will fire post-deploy.
script location - Updates will fire on next sequential workflow, not post-deploy.

When Adding
pantheon.yml - Updates will fire on the next sequential workflow, not post-deploy.
scripts - Updates will fire on the next sequential workflow.

**Comment by joshkoenig** [comment]
@bmackinney can we think about adding this to the doc?

**Comment by joshkoenig** [comment]
This is now in the README.
