### ISSUE TITLE
Feature request: Site level object store

### ISSUE THREAD

**Issue by mikemilano** [pantheon-systems/quicksilver-examples#29]
It seems like a common task is going to be storing config data for the scripts. (credentials, service endpoints, etc...)

JSON configs are fine for static data, but it would be pretty nice for the scripts to have access to a site-level object store for both static and dynamic use.

Besides an easier way to store and retrieve script data, it would be nice if the data persisted at a global (site) level rather than an environment level. This way when a file system is blown out by a copy, the data would not be lost.

If a site level db service is out of the question, maybe access to write files at a site level directory would be sufficient. The author could maintain an sqlite db if they needed anything fancy. A site level service with a simple getter/setter wrapper functions available to the scripts would provide for a nice way to standardize though.

**Comment by joshkoenig** [comment]
Probably out of scope for now. For real secrets, we suggest something like Lockr. 

https://pantheon.io/blog/key-drupal-security
