### ISSUE TITLE
Environment url & protocol in payload

### ISSUE THREAD

**Issue by mikemilano** [pantheon-systems/quicksilver-examples#34]
Having the environment url and protocol in the payload would be nice.

Use case: post-deployment url status checker (which could also serve as a cache warmer)

An array of URLs are defined to be checked with Guzzle for returning status 200 after deployment.

It would be nice if the base environment url was available, including protocol if the site is secured (for sites that are setup to restrict requests to https).

If this were the case, the script would only need one set of uris defined, which appended a base url, for status checking across multiple environments.

**Comment by joshkoenig** [comment]
The environment should be in `$_ENV` and shortly it should be super-reliable to have a pattern-derived domain name assumed.

If we see a lot of custom env domains, we'll need to wait for a way to mark one as the "primary" domain before we could send it along. As it stands right now we actually keep a list, but it's an unsorted list which isn't super helpful here.
