### ISSUE TITLE
Deploy Message that fires "Before" is Different from "After"

### ISSUE THREAD

**Issue by jordan8037310** [pantheon-systems/quicksilver-examples#44]
When running a script before deployment starts, the correct deployment message should be displayed. Right now it is displaying the $annotation from the previous deployment. 

![image](https://cloud.githubusercontent.com/assets/3300713/12843793/832c9ba6-cbb0-11e5-9974-971fa57e0bcb.png)

Whether implementing a hook before or after a deployment, references to the $annotation should be consistent, right?

**Comment by joshkoenig** [comment]
Good catch. This is why we need to get the deploy message from the payload, not the git repo that the script can peek at. I think this should be available soon. (paging @kibra?)

**Comment by joshkoenig** [comment]
Huzzah! It's in.

`$_POST['deploy_message']` exists now. I'll update these scripts.

**Comment by jordan8037310** [comment]
awesome @joshkoenig, will be updating mine as well. Thanks!

**Comment by joshkoenig** [comment]
We also have added two more attributes to the payload:

`stage` - will tell you "before" or "after"
`qs_description` - the description from your `yaml` file if you ever should need to use it.
