### ISSUE TITLE
Example wanted: Configuration import for Drupal 8

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/quicksilver-examples#59]
I expect that many Drupal 8 sites will want to automatically import configuration present in code upon deployments to live and test (and possibly database clones). I see this use case as the Drupal 8 equivalent of the "Features revert all" example that we have for Drupal 7: https://github.com/pantheon-systems/quicksilver-examples/tree/master/drush_revert_features

The code for this example might be as simple as a usage of `drush cim`.

**Comment by stevector** [comment]
I'm going to start on this example.

**Comment by stevector** [comment]
There is now an example that is ready to be tested in #64.

**Comment by joshkoenig** [comment]
Booyah! Merged.
