### ISSUE TITLE
Example wanted: Wordpress CFM 

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/quicksilver-examples#60]
WordPress has a plugin analogous to Drupal's Features module: https://wordpress.org/plugins/wp-cfm/

Just as we have an example for deploying configuration via Features (https://github.com/pantheon-systems/quicksilver-examples/tree/master/drush_revert_features) we should have an example for WordPress CFM.

**Comment by stevector** [comment]
Should be covered by https://github.com/pantheon-systems/quicksilver-examples/pull/58

**Comment by ataylorme** [comment]
#58 has been merged, closing this out
