### ISSUE TITLE
Example wanted: Post Solr schema after creating new multidev env (Drupal)

### ISSUE THREAD

**Issue by ordavidil** [pantheon-systems/quicksilver-examples#62]
Hey,

Do you have any suggestions of how to post pantheon solr schema after cloning db?

Thanks ahead.

**Comment by ataylorme** [comment]
Hi @ordavidil,
If you are using the [Solr Power WordPress](https://wordpress.org/plugins/solr-power/) plugin schema can be posted with [WP-CLI](http://wp-cli.org/) using the command `wp solr repost-schema`.

You can see this being done in the recently added [`wp_solr_index` example](https://github.com/pantheon-systems/quicksilver-examples/blob/master/wp_solr_index/wp_solr_power_index.php#L4).

That example indexes Solr after creating a new multidev but you could adapt it to repost the schema file after a DB clone.

**Comment by ordavidil** [comment]
Hey @ataylorme , thanks for replying!
I'm using Drupal though :)

**Comment by ataylorme** [comment]
@ordavidil which version of Drupal and which Solr module are you using? Perhaps what you are using has a similar drush command.

**Comment by ordavidil** [comment]
Drupal - 7.43
pantheon_apachesolr - v1.0

**Comment by ataylorme** [comment]
Hi @ordavidil,
Unfortunately that module doesn't have drush support at the moment. A pull request to add drush support to the module is most welcome. Once that is in place I can help you with the Quicksilver functionality.

cc @greg-1-anderson

**Comment by ordavidil** [comment]
well, basically, the problem is only when creating new multidev env, since there is no trigger for that, and the _clone_db_ flow is not triggered on this event, although part of it is cloning the DB from a different env.

**Comment by ataylorme** [comment]
@ordavidil There is a Quicksilver hook that fires when creating a new multidev environment. It's `create_cloud_development_environment` and was part of our [recent Quicksilver updates](https://pantheon.io/blog/advanced-site-configuration-new-hooks-quicksilver). You can view all the available hooks in [this doc](https://pantheon.io/docs/quicksilver/).

It's being used in the [`wp_solr_index` example](https://github.com/pantheon-systems/quicksilver-examples/blob/master/wp_solr_index/wp_solr_power_index.php#L4) I posted previously to index Solr when a new multidev is created. You could also use it to post the schema file. This will be easiest once there is a drush command to do so.

You could also do it with just PHP. [Here's how the Solr Power WordPress plugin posts `schema.xml`](https://github.com/pantheon-systems/solr-power/blob/b80446e28e166d26fe5573c65dd7da0b5fd517e4/includes/class-solrpower-api.php#L45:L108) for reference.

Hope this helps.

**Comment by ordavidil** [comment]
I'm waiting for this hook more than 6 months,  thanks a lot !  :)
