### ISSUE TITLE
Example wanted: Setting New Relic Apdex configuration upon Multidev creation

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/quicksilver-examples#86]
I've been doing some profiling of PHP 5.6 vs. PHP 7 and in doing so, I've been creating a lot of Multidev environments.

As I do, I'm reminded that the Apdex T value and alert policy is unique for each environment. If there isn't a way to set default values in New Relic for new Multidevs, it should be fairly trivial to do so with with the REST API called from Quicksilver.

For example:

```
curl -X PUT 'https://api.newrelic.com/v2/applications/123456789.json' \
     -H 'X-Api-Key:12344567890QWERQASDFASDFZXCV' -i \
     -H 'Content-Type: application/json' \
     -d \
'{
  "application": {
    "name": "string",
    "settings": {
      "app_apdex_threshold": "1",
      "end_user_apdex_threshold": "3",
      "enable_real_user_monitoring": "boolean"
    }
  }
}' 
```

@ari-gold, @joshkoenig, @ataylorme, Should this be done some other way? If not, I'll make a PR to add this example.

**Comment by joshkoenig** [comment]
This is correct IMHO. It would also be a great example.

Currently we have one challenge in that we rely on NR's auto-provisioning to set up applications when new environments report in, so we don't know the application id number ahead of time.

We might have to get creative to work around that, but I think it would be worth reviewing the API to see if we can to anything - maybe we can register the app name (`accountName_envName`) on multidev creation to get the ID, and then use that to configure things?

**Comment by stevector** [comment]
I was assuming that we could run in the "after" phase of multidev creation. I've been using the [deploy marker example](https://github.com/pantheon-systems/quicksilver-examples/blob/master/new_relic_deploy/new_relic_deploy.php) on Multidevs that I'm provisioning with a script and it has worked well. I was planning on retrieving the `app_name` and `api_key` with the same technique as is used there.

I'll just try it and see what happens.

**Comment by stevector** [comment]
It works. I'll have a cleaned up PR later in the week.

**Comment by stevector** [comment]
PR started here: https://github.com/pantheon-systems/quicksilver-examples/pull/89. Testers wanted.
